### ISSUE TITLE
TANGキット制作

### ISSUE THREAD

**Issue by ShunjiHashimoto** [ShunjiHashimoto/tang_task#19]
要求
コントローラで操作できるようにする
色認識で追従する
納期 9/30

**Comment by ShunjiHashimoto** [comment]
https://docs.google.com/spreadsheets/d/1q-YsTP3jejp-_rPOf7N6AzW_tEbbk9OsKEjhasZL6b8/edit?fbclid=IwAR1graRbH-fkm_6JGQ0NAwUR-l9usu4x2VSj73hyS0wtlbp3Ar9I_iPL1dk#gid=0
部品リスト作成した  
これでおおよそオッケーなはず。週末にキット準備進める  
それまでに速度制御完成させる

**Comment by ShunjiHashimoto** [comment]
Ubuntu20.04をinstall

https://cdimage.ubuntu.com/releases/20.04/release/

参考）https://kledgeb.blogspot.com/2022/02/xubuntu-8-raspberry-pi-4xubuntu.html

**Comment by ShunjiHashimoto** [comment]
https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#5-install-a-desktop  
こちらを参考に、xubuntu20.04をinstall

**Comment by ShunjiHashimoto** [comment]
https://ar-ray.hatenablog.com/entry/2021/06/08/180000
xubuntuが上記の方法だと失敗したので、こちらの方法を試す、すでにROSが入ったimgファイル

**Comment by ShunjiHashimoto** [comment]
エラー1
```bash
ubuntu@ubuntu:~$ sudo apt-get -y install python-rpi.gpio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-rpi.gpio is already the newest version (0.6.5-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 1223 not upgraded.
ubuntu@ubuntu:~$ roslaunch tang_bringup tang_bringup.launch 
... logging to /home/ubuntu/.ros/log/c918722e-5524-11ee-9c85-1546eb62e837/roslaunch-ubuntu-22552.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:36657/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /tang_control/max_area: 130000
 * /tang_control/max_area_red: 167
 * /tang_control/speed: 50

NODES
  /
    tang_control (tang_control/tang_control.py)

auto-starting new master
process[master]: started with pid [22572]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c918722e-5524-11ee-9c85-1546eb62e837
process[rosout-1]: started with pid [22586]
started core service [/rosout]
process[tang_control-2]: started with pid [22593]
ubuntu@ubuntu:~$ sudo pip3 install rpi.gpio
```

**Comment by ShunjiHashimoto** [comment]
エラー２
```bash
ubuntu@ubuntu:~$ roslaunch tang_bringup tang_bringup.launch 
... logging to /home/ubuntu/.ros/log/7aaabe12-5524-11ee-9c85-1546eb62e837/roslaunch-ubuntu-21841.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:33035/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /tang_control/max_area: 130000
 * /tang_control/max_area_red: 167
 * /tang_control/speed: 50

NODES
  /
    tang_control (tang_control/tang_control.py)

auto-starting new master
process[master]: started with pid [21868]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7aaabe12-5524-11ee-9c85-1546eb62e837
process[rosout-1]: started with pid [21889]
started core service [/rosout]
process[tang_control-2]: started with pid [21892]
Traceback (most recent call last):
  File "/home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py", line 6, in <module>
    import spidev
ModuleNotFoundError: No module named 'spidev'
[tang_control-2] process has died [pid 21892, exit code 1, cmd /home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py __name:=tang_control __log:=/home/ubuntu/.ros/log/7aaabe12-5524-11ee-9c85-1546eb62e837/tang_control-2.log].
log file: /home/ubuntu/.ros/log/7aaabe12-5524-11ee-9c85-1546eb62e837/tang_control-2*.log
ubuntu@ubuntu:~$  sudo pip3 install spidev
```

**Comment by ShunjiHashimoto** [comment]
エラー３
```bash
ubuntu@ubuntu:~$ roslaunch tang_bringup tang_bringup.launch 
... logging to /home/ubuntu/.ros/log/39099496-5525-11ee-9c85-1546eb62e837/roslaunch-ubuntu-23495.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:35157/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /tang_control/max_area: 130000
 * /tang_control/max_area_red: 167
 * /tang_control/speed: 50

NODES
  /
    tang_control (tang_control/tang_control.py)

auto-starting new master
process[master]: started with pid [23538]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 39099496-5525-11ee-9c85-1546eb62e837
process[rosout-1]: started with pid [23574]
started core service [/rosout]
process[tang_control-2]: started with pid [23578]
Traceback (most recent call last):
  File "/home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py", line 9, in <module>
    import lcd_display
ModuleNotFoundError: No module named 'lcd_display'
[tang_control-2] process has died [pid 23578, exit code 1, cmd /home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py __name:=tang_control __log:=/home/ubuntu/.ros/log/39099496-5525-11ee-9c85-1546eb62e837/tang_control-2.log].
log file: /home/ubuntu/.ros/log/39099496-5525-11ee-9c85-1546eb62e837/tang_control-2*.log
c^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by ShunjiHashimoto** [comment]
lcd_displayのスクリプトを移動させたら解決
エラー4
```bash
ubuntu@ubuntu:~$ roslaunch tang_bringup tang_bringup.launch 
... logging to /home/ubuntu/.ros/log/a2068ec2-5525-11ee-9c85-1546eb62e837/roslaunch-ubuntu-24132.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:36487/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /tang_control/max_area: 130000
 * /tang_control/max_area_red: 167
 * /tang_control/speed: 50

NODES
  /
    tang_control (tang_control/tang_control.py)

auto-starting new master
process[master]: started with pid [24156]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a2068ec2-5525-11ee-9c85-1546eb62e837
process[rosout-1]: started with pid [24177]
started core service [/rosout]
process[tang_control-2]: started with pid [24180]
Traceback (most recent call last):
  File "/home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py", line 9, in <module>
    import lcd_display
  File "/home/ubuntu/ros1_ws/src/tang/tang_control/scripts/lcd_display.py", line 24, in <module>
    import smbus
ModuleNotFoundError: No module named 'smbus'
[tang_control-2] process has died [pid 24180, exit code 1, cmd /home/ubuntu/ros1_ws/src/tang/tang_control/scripts/tang_control.py __name:=tang_control __log:=/home/ubuntu/.ros/log/a2068ec2-5525-11ee-9c85-1546eb62e837/tang_control-2.log].
log file: /home/ubuntu/.ros/log/a2068ec2-5525-11ee-9c85-1546eb62e837/tang_control-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by ShunjiHashimoto** [comment]
pigpioのインストールで少し躓いた、後ほど書く
```bash
$ sudo apt install python3-pigpio
```
これで解決

**Comment by ShunjiHashimoto** [comment]
pigpioはこれで解決した

bash
Copy code
sudo apt update
sudo apt install build-essential
git clone https://github.com/joan2937/pigpio
cd pigpio
make
sudo make install
このプロセスが完了すると、pigpiod デーモンを起動するための pigpiod コマンドが利用可能になります。再度以下のコマンドを実行してデーモンを起動してください：

bash
Copy code
sudo pigpiod
このコマンドを実行した後、pigpiod デーモンが成功裏に起動していることを確認できるはずです。

**Comment by ShunjiHashimoto** [comment]
遠隔操縦の部分の確認まで完了した。
あとは赤色追従時に速度制御が可能であるか確認できれば、組み立て、はんだ付けなどを行う

**Comment by ShunjiHashimoto** [comment]
- JST SM
  - 6ピン x2
  - 5ピン x10セット
- JST PH
  - 4ピン 2セット
- JST XH 
  - 5ピン 6セット
  - 4ピン 2セット
- レベル変換基板
  - 1セット
- USBオス
  - 1本
- M3ネジ,長さ5mm
  - 10本くらい
- ユリアネジ, 長さ5mm
  - 5本くらい

**Comment by ShunjiHashimoto** [comment]
バッテリーボックスは別途注文してもらうとして、今回は自分のやつを使いまわす予定

**Comment by ShunjiHashimoto** [comment]
他に必要なもの
- M2.6x7mmのスペーサ
- CuGoのコネクタ
  - 防水型ギボシ端子
  - オスの方は直径9mm程度
- M3ネジ 5mm

**Comment by ShunjiHashimoto** [comment]
配線残タスク

- [x] LCDディスプレイ取り付け
- [x] ファンx2取り付け
- [x] バッテリー電圧表示器の接着
- [x] グロメット取り付け
- [ ] （IMU取り付け）

**Comment by ShunjiHashimoto** [comment]
M5の20mm4本

**Comment by ShunjiHashimoto** [comment]
M6 23mm以上の長さ 1本
カメラ用

**Comment by ShunjiHashimoto** [comment]
モータ防水コネクタx3

**Comment by ShunjiHashimoto** [comment]
残タスク
- [ ] テスターチェック
- [ ] 火入れ
- [ ] 各スクリプトの動作確認
- [ ] テストサンプル開発？

**Comment by ShunjiHashimoto** [comment]
残タスク

- [ ] エンコーダ値取得のバグ修正
- [ ] LCDに文字を表示させる
- [x] 自動起動スクリプト作成
- [ ] 緑色検出に変更する資料作成
- [x] 長時間つけると消える問題

**Comment by ShunjiHashimoto** [comment]
pigpioで毎回sudo pigpiodを実行させないといけなったので、自動でできるようにした
https://l-w-i.net/t/raspbian/pigpio_001.txt

**Comment by ShunjiHashimoto** [comment]
自動起動スクリプト作成
```bash
(noetic):~/ros1_ws/src/tang/.shellscripts$ cat tang_bringup.sh 
#!/bin/bash

expect -c "
  spawn bash
  expect \"$\"
  send \"roslaunch tang_bringup tang_bringup.launch\n\"
  interact
"
```
```bash
(noetic):~/ros1_ws/src/tang/.shellscripts$ cat bringup_raspi.sh 
#!/bin/bash
echo "start bringup tang bringup"
gnome-terminal --geometry=80x15+20+0 "Tab1" -- bash -c "cd /home/ubuntu/ros1_ws/src/tang/.shellscripts; sh tang_bringup.sh;"
```
自動起動の設定はGUI上で行った

**Comment by ShunjiHashimoto** [comment]
エンコーダの仕組み
https://chat.openai.com/c/e780ad2e-aa81-4adb-8876-09c6804d1267

**Comment by ShunjiHashimoto** [comment]
残タスク

- [x] 開発用ノートPCのUbuntuインストール
- [x] 速度制御のデバッグ作業
- [ ] LCDモジュールの表示
- [ ] ラベル貼り
- [x] カメラの撮影画像が白飛びする
- [ ]

**Comment by ShunjiHashimoto** [comment]
カメラの白飛び問題は、新たな高価なUSBカメラを買って解決を試みる
また、90→150の視野角を持つので、より広い範囲を見ることが可能

**Comment by ShunjiHashimoto** [comment]
非常停止からの復帰時に速度制御がばぐる
カラー画像問題は解消した

**Comment by ShunjiHashimoto** [comment]
あとちょっとラグい

**Comment by ShunjiHashimoto** [comment]
非常停止時の振る舞いはおおよそ修正できた、あとは動かしてみてパラメータ調整するのと、追従のときの指令値の与え方をリファクタする

**Comment by ShunjiHashimoto** [comment]
残タスク

- [ ] 速度設定を一つのファイルにまとめる

- [ ]  屋外で動作確認する

**Comment by ShunjiHashimoto** [comment]
こちらは一旦ペンディングになりそう、ドキュメント整理は必要かも、また確認する

**Comment by ShunjiHashimoto** [comment]
READMEに配線図載せたいので、自宅のデスクトップPCで作成した配線図を作り直す必要あり

**Comment by ShunjiHashimoto** [comment]
残タスク
- 緊急停止モードが正常に動作しているか確認する
  - もし厳しければPIDゲインにlimitを設けて対処する

**Comment by ShunjiHashimoto** [comment]
残タスク
- 緊急停止モードが正常に動作しているか確認する
  - もし厳しければPIDゲインにlimitを設けて対処する

**Comment by ShunjiHashimoto** [comment]
残タスク

- [ ] 緊急停止モードが正常に動作しているか確認する

  - もし厳しければPIDゲインにlimitを設けて対処する

**Comment by ShunjiHashimoto** [comment]
動作確認はまだできていないけど、明日頑張る、
ダンボール準備と両面テープが必要

**Comment by ShunjiHashimoto** [comment]
とりあえず納品できた！お疲れ様でした
